name: CodeQL

on:
  push:
    branches:
      - "**" # 在所有分支上運行
  pull_request:
    branches:
      - "**"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      runs: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
